settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.swds.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: k2_swds.cf
    name: k2_swds.cf
    description: '' # default=empty
    url: 'https://swds.cf/v/' # URL to fetch
    method: GET # default=GET
    expectStatus: 400 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: kr.swds.cf
    name: kr.swds.cf
    description: ' '
    url: 'https://kr.swds.cf/v/'
    method: GET
    expectStatus: 400
    linkable: false

  - id: k3.swds.cf
    name: k3.swds.cf
    description: ' '
    url: 'https://k3.swds.cf/v/'
    method: GET
    expectStatus: 400
    linkable: false

  - id: hk.swds.cf
    name: hk.swds.cf
    description: ' '
    url: 'https://hk.swds.cf/v/'
    method: GET
    expectStatus: 400
    linkable: false
